from localdirectory.plugins.cqc import _discover_csv_url, _parse_directory_csv


def test_discover_current_cqc_csv_prefers_live_directory():
    html = """
    <html><body>
      <a href="/archive/deactivated.csv">Deactivated locations CSV</a>
      <a href="/sites/default/files/202608_CQC_directory.csv">CQC care directory - csv</a>
    </body></html>
    """
    assert _discover_csv_url(html, "https://www.cqc.org.uk/about-us/transparency/using-cqc-data") == (
        "https://www.cqc.org.uk/sites/default/files/202608_CQC_directory.csv"
    )


def test_parse_cqc_csv_filters_radius_and_does_not_map_homecare_office():
    raw = """Generated by CQC\r\nCurrent locations\r\nOpen Government Licence\r\n\r\nLocation ID,Location Name,Location Web Address,Location Telephone Number,Location Type/Sector,Location Primary Inspection Category,Location Street Address,Location Address Line 2,Location City,Location County,Location Postal Code,Location Latitude,Location Longitude,Provider Name,Provider Companies House Number,Provider Charity Number\r\nlew1,Lewes Dental Centre,https://dentist.example,01273 000001,Primary care organisations,Dentist,1 High Street,,Lewes,East Sussex,BN7 2AA,50.8739,0.0088,Dentist Provider Ltd,01234567,\r\nlew2,Lewes Home Care,https://homecare.example,01273 000002,Adult social care,Homecare agency,2 High Street,,Lewes,East Sussex,BN7 2AB,50.8740,0.0090,Care Provider Ltd,07654321,1234567\r\nfar1,Far Away Hospital,https://far.example,01273 000003,Hospital,Hospital,1 Distant Road,,London,London,SW1A 1AA,51.5010,-0.1416,Far Provider Ltd,11111111,\r\n""".encode()

    records = _parse_directory_csv(
        raw,
        centre_latitude=50.8739,
        centre_longitude=0.0088,
        radius_km=16.0934,
        postcode_area="BN7",
    )

    assert [record.name for record in records] == ["Lewes Dental Centre", "Lewes Home Care"]

    dentist = records[0]
    assert dentist.listing_type == "place"
    assert dentist.primary_category == "health_care"
    assert dentist.address_public is True
    assert dentist.latitude == 50.8739
    assert dentist.regulator_ids["cqc"] == "lew1"
    assert dentist.sources[0].source_class == "A"

    homecare = records[1]
    assert homecare.listing_type == "service_provider"
    assert homecare.address_public is False
    assert homecare.latitude is None
    assert homecare.longitude is None
    assert homecare.service_area == ["Lewes"]
    assert homecare.regulator_ids["charity_commission"] == "1234567"
    assert "cqc_service_office_not_mapped" in homecare.quality_flags


def test_parse_cqc_csv_allows_local_postcode_for_missing_coordinates():
    raw = """note\nLocation ID,Location Name,Location Postal Code,Location Primary Inspection Category\nlew3,Lewes Clinic,BN7 1AA,Clinic\n""".encode()
    records = _parse_directory_csv(
        raw,
        centre_latitude=50.8739,
        centre_longitude=0.0088,
        radius_km=16.0934,
        postcode_area="BN7",
    )
    assert len(records) == 1
    assert records[0].name == "Lewes Clinic"
    assert records[0].latitude is None
